export const optionsArray = [
    { id: 1, name: "13 de Junio" },
    { id: 2, name: "17 de Diciembre" },
    { id: 3, name: "1ra de Mayo" },
    { id: 4, name: "20 de Julio" },
    { id: 5, name: "20 de Octubre" },
    { id: 6, name: "6 de Febrero" },
    { id: 7, name: "7 de Agosto" },
    { id: 8, name: "8 de Diciembre" },
    { id: 9, name: "8 de Febrero" },
    { id: 10, name: "8 de Noviembre" },
    { id: 11, name: "Acacias" },
    { id: 12, name: "Acodis" },
    { id: 13, name: "Alambique" },
    { id: 14, name: "Alfonso López" },
    { id: 15, name: "Alto Jardín" },
    { id: 16, name: "Altos de Santa Rita" },
    { id: 17, name: "Altos Delicias" },
    { id: 18, name: "Altos Santa Cruz" },
    { id: 19, name: "Altos Simón Bolivar" },
    { id: 20, name: "Altos Villa Concha" },
    { id: 21, name: "Andra Doría" },
    { id: 22, name: "Andrea Carolina" },
    { id: 23, name: "Arhuacos" },
    { id: 24, name: "Asocom" },
    { id: 25, name: "Av. Del Río (III Etapa)" },
    { id: 26, name: "Av. Libertador - Entrada de Bastidas" },
    { id: 27, name: "Av. Libertador - P. Mamatoco" },
    { id: 28, name: "Balcones del Libertador" },
    { id: 29, name: "Barrio Obrero" },
    { id: 30, name: "Bastidas" },
    { id: 31, name: "Bavaria" },
    { id: 32, name: "Bavaria Reservado" },
    { id: 33, name: "Belen" },
    { id: 34, name: "Bella Vista" },
    { id: 35, name: "Bellavista" },
    { id: 36, name: "Bello Sol" },
    { id: 37, name: "Benjamín Alzate" },
    { id: 38, name: "Betania" },
    { id: 39, name: "Bolivariana" },
    { id: 40, name: "Bolívar" },
    { id: 41, name: "Boston" },
    { id: 42, name: "Boulevard de la 19" },
    { id: 43, name: "Brisas del Lago" },
    { id: 44, name: "Buenos Aires" },
    { id: 45, name: "Cantillito I" },
    { id: 46, name: "Cantillito II" },
    { id: 47, name: "Cantillito III" },
    { id: 48, name: "Cantillito IV" },
    { id: 49, name: "Caribe Inn" },
    { id: 50, name: "Cañaveral" },
    { id: 51, name: "Centro" },
    { id: 52, name: "Centro Histórico" },
    { id: 53, name: "Cerro Intermedio" },
    { id: 54, name: "Cerro La Llorona" },
    { id: 55, name: "Cerro La Virgen" },
    { id: 56, name: "Cerro M" },
    { id: 57, name: "Chimila 1" },
    { id: 58, name: "Chimila 2" },
    { id: 59, name: "Ciudadela 29 de Julio" },
    { id: 60, name: "Conjunto Residencial Canarias" },
    { id: 61, name: "Corea" },
    { id: 62, name: "Corintio" },
    { id: 63, name: "Costa Verde" },
    { id: 64, name: "Cristal" },
    { id: 65, name: "Cristalina" },
    { id: 66, name: "Cristo Rey" },
    { id: 67, name: "Cristo Rey (Nacho Vives)" },
    { id: 68, name: "Curinca" },
    { id: 69, name: "César Mendoza" },
    { id: 70, name: "Daniel Sánchez" },
    { id: 71, name: "Divino niño" },
    { id: 72, name: "Doce de Octubre" },
    { id: 73, name: "Don Jaca Alto" },
    { id: 74, name: "Eduardo Gutiérrez" },
    { id: 75, name: "El Bosque" },
    { id: 76, name: "El Carmen" },
    { id: 77, name: "El Cisne" },
    { id: 78, name: "El Cundi" },
    { id: 79, name: "El Mango" },
    { id: 80, name: "El Olivo" },
    { id: 81, name: "El Pantano" },
    { id: 82, name: "El Piñon" },
    { id: 83, name: "El Pradito" },
    { id: 84, name: "El Prado" },
    { id: 85, name: "El Pueblito" },
    { id: 86, name: "El Recreo" },
    { id: 87, name: "El Refugio" },
    { id: 88, name: "El Socorro" },
    { id: 89, name: "El Territorial" },
    { id: 90, name: "El Trébol" },
    { id: 91, name: "El Valle de Gaira" },
    { id: 92, name: "Elvira María" },
    { id: 93, name: "Ensenada Juan XXIIII 1" },
    { id: 94, name: "Ensenada Juan XXIIII 2" },
    { id: 95, name: "Ensenada Olaya" },
    { id: 96, name: "Esmeralda" },
    { id: 97, name: "Florida" },
    { id: 98, name: "Gaira - Centro" },
    { id: 99, name: "Galán" },
    { id: 100, name: "Gauchovand" },
    { id: 101, name: "Glicia" },
    { id: 102, name: "Invasión Nueva" },
    { id: 103, name: "Juan XXIII" },
    { id: 104, name: "La Chivera" },
    { id: 105, name: "La Concepción II" },
    { id: 106, name: "La esperanza" },
    { id: 107, name: "La Estrella" },
    { id: 108, name: "La Eva" },
    { id: 109, name: "La Gran Via" },
    { id: 110, name: "La Logia" },
    { id: 111, name: "La Lucha" },
    { id: 112, name: "La Magdalena" },
    { id: 113, name: "La Paz" },
    { id: 114, name: "La Quemada" },
    { id: 115, name: "La Quinina" },
    { id: 116, name: "La Rosalía" },
    { id: 117, name: "La Tenería" },
    { id: 118, name: "La Unión" },
    { id: 119, name: "Lago Dulcino" },
    { id: 120, name: "Las Américas" },
    { id: 121, name: "Las Colinas" },
    { id: 122, name: "Las Malvinas" },
    { id: 123, name: "Las Palmeras" },
    { id: 124, name: "Las Vegas" },
    { id: 125, name: "Libano 2000" },
    { id: 126, name: "Libertador" },
    { id: 127, name: "Limón" },
    { id: 128, name: "Loma Fresca" },
    { id: 129, name: "Los Alcázares" },
    { id: 130, name: "Los Almendros" },
    { id: 131, name: "Los Cocos" },
    { id: 132, name: "Los Faroles" },
    { id: 133, name: "Los Fundadores" },
    { id: 134, name: "Los Laureles" },
    { id: 135, name: "Los Lirios" },
    { id: 136, name: "Los Maguitos - Comuna 4" },
    { id: 137, name: "Los Nogales" },
    { id: 138, name: "Los Pinos" },
    { id: 139, name: "Los Troncos" },
    { id: 140, name: "Los Trupillos" },
    { id: 141, name: "Los Ángeles" },
    { id: 142, name: "Loteo Graciela Riascos" },
    { id: 143, name: "Luis R. Calvo" },
    { id: 144, name: "Luz del Mundo" },
    { id: 145, name: "Mamatoco" },
    { id: 146, name: "Manguitos" },
    { id: 147, name: "Manzanares" },
    { id: 148, name: "Martinete" },
    { id: 149, name: "María Eugenia" },
    { id: 150, name: "Mercado Público" },
    { id: 151, name: "Miguel Pinedo" },
    { id: 152, name: "Minuto de Dios" },
    { id: 153, name: "Miraflores" },
    { id: 154, name: "Miramar" },
    { id: 155, name: "Modelo" },
    { id: 156, name: "Montpellier" },
    { id: 157, name: "Municipal" },
    { id: 158, name: "Murallas" },
    { id: 159, name: "Norte" },
    { id: 160, name: "Nueva Betel" },
    { id: 161, name: "Nueva Colombia" },
    { id: 162, name: "Nueva Galicia" },
    { id: 163, name: "Nueva Granada" },
    { id: 164, name: "Nueva Mansión" },
    { id: 165, name: "Nueva Venecia" },
    { id: 166, name: "Nuevo Armero" },
    { id: 167, name: "Nuevo Jardín" },
    { id: 168, name: "Nuevo Milenio" },
    { id: 169, name: "Oasis" },
    { id: 170, name: "Obrero" },
    { id: 171, name: "OLaya Herrera" },
    { id: 172, name: "Once de Noviembre" },
    { id: 173, name: "Ondas del Caibe" },
    { id: 174, name: "Pamplonita" },
    { id: 175, name: "Pando" },
    { id: 176, name: "Paraiso" },
    { id: 177, name: "Pastrana" },
    { id: 178, name: "Pepe Hurtado" },
    { id: 179, name: "Perehuétano" },
    { id: 180, name: "Philadelfia" },
    { id: 181, name: "Porvenir" },
    { id: 182, name: "Postobón" },
    { id: 183, name: "Puerto Mosquito" },
    { id: 184, name: "Quebrada M." },
    { id: 185, name: "Recreo - Comuna 4" },
    { id: 186, name: "Rodadero Tradicional" },
    { id: 187, name: "Rodrigo Ahumada" },
    { id: 188, name: "Salamanca" },
    { id: 189, name: "Salvador" },
    { id: 190, name: "San Fernando" },
    { id: 191, name: "San Fráncisco" },
    { id: 192, name: "San Jorge" },
    { id: 193, name: "San José" },
    { id: 194, name: "San Martín" },
    { id: 195, name: "San Pablo" },
    { id: 196, name: "San Pedro Alejandrino" },
    { id: 197, name: "San Ramon" },
    { id: 198, name: "San Tropel" },
    { id: 199, name: "Santa Catalina" },
    { id: 200, name: "Santa Cecilia" },
    { id: 201, name: "Santa Clara" },
    { id: 202, name: "Santa Cruz" },
    { id: 203, name: "Santa Helena" },
    { id: 204, name: "Santa Lucia" },
    { id: 205, name: "Santa Mónica" },
    { id: 206, name: "Santa Rita" },
    { id: 207, name: "Santa Verónica" },
    { id: 208, name: "Santafé" },
    { id: 209, name: "Sarabanda" },
    { id: 210, name: "Simón Bolívar" },
    { id: 211, name: "Sircacia" },
    { id: 212, name: "Taganga" },
    { id: 213, name: "Tamaca" },
    { id: 214, name: "Taminaca 1" },
    { id: 215, name: "Taminaca 2" },
    { id: 216, name: "Tayrona 1" },
    { id: 217, name: "Tayrona 2" },
    { id: 218, name: "Tejares del Libertador" },
    { id: 219, name: "Tierra Baja" },
    { id: 220, name: "Timayuí I" },
    { id: 221, name: "Timayuí II" },
    { id: 222, name: "Timayuí III" },
    { id: 223, name: "Totumo" },
    { id: 224, name: "Trece de Junio" },
    { id: 225, name: "Tres Puentes" },
    { id: 226, name: "Urbanización Alejandrina" },
    { id: 227, name: "Urbanización Autopista" },
    { id: 228, name: "Urbanización Bavaria Country" },
    { id: 229, name: "Urbanización Berlín" },
    { id: 230, name: "Urbanización Boulevard del Río" },
    { id: 231, name: "Urbanización Caracas" },
    { id: 232, name: "Urbanización Colon" },
    { id: 233, name: "Urbanización El Parque" },
    { id: 234, name: "Urbanización El Refugio" },
    { id: 235, name: "Urbanización Elvia Mejía" },
    { id: 236, name: "Urbanización Garagoa" },
    { id: 237, name: "Urbanización Guido" },
    { id: 238, name: "Urbanización Hábitat" },
    { id: 239, name: "Urbanización Las Delicias" },
    { id: 240, name: "Urbanización Los Cerros" },
    { id: 241, name: "Urbanización Mayorga" },
    { id: 242, name: "Urbanización Nuevo Jardín" },
    { id: 243, name: "Urbanización Peréz Dávila" },
    { id: 244, name: "Urbanización Pradera" },
    { id: 245, name: "Urbanización Reposo" },
    { id: 246, name: "Urbanización Riascos" },
    { id: 247, name: "Urbanización San Carlos" },
    { id: 248, name: "Urbanización Santa Elena" },
    { id: 249, name: "Urbanización Santa Lucia" },
    { id: 250, name: "Urbanización Santa Rita" },
    { id: 251, name: "Urbanización Silvia Rosa" },
    { id: 252, name: "Urbanización Veracruz" },
    { id: 253, name: "Urbanización Villa del Mar" },
    { id: 254, name: "Urbanización Villas de Alejandría" },
    { id: 255, name: "Urbanzicación El Río" },
    { id: 256, name: "Urbnaización Guerrero" },
    { id: 257, name: "Veinte de Enero" },
    { id: 258, name: "Vereda Mosquito" },
    { id: 259, name: "Villa Aurora" },
    { id: 260, name: "Villa Berlín" },
    { id: 261, name: "Villa Betel" },
    { id: 262, name: "Villa Campo" },
    { id: 263, name: "Villa Dania" },
    { id: 264, name: "Villa del Carmen" },
    { id: 265, name: "Villa del Mar" },
    { id: 266, name: "Villa del Rio" },
    { id: 267, name: "Villa del Rosario" },
    { id: 268, name: "Villa Ely" },
    { id: 269, name: "Villa Italia" },
    { id: 270, name: "Villa Marbella" },
    { id: 271, name: "Villa Marina" },
    { id: 272, name: "Villa Mercedes" },
    { id: 273, name: "Villa Sara" },
    { id: 274, name: "Villa Tabla" },
    { id: 275, name: "Villa Tanga - Puente" },
    { id: 276, name: "Villa Toledo" },
    { id: 277, name: "Villa Trinidad" },
    { id: 278, name: "Vista del Mar" },
    { id: 279, name: "Vista Hermosa" },
    { id: 280, name: "Yucal 1" },
    { id: 281, name: "Yucal 2" },
    { id: 282, name: "Zona del Mercado" }
  ];


  